-- Kharwa - schema
--
-- Paste this whole file into the Supabase SQL Editor and run it.
-- It is idempotent: re-running it is safe and will not drop data.
--
-- Note on security: there is no login in this app, so the anon role is granted
-- full read/write on every table. Anyone who has the project URL and anon key
-- can read and change the logs. That is a deliberate trade-off for a two-person
-- app on an unlisted URL.

-- ---------------------------------------------------------------- people -----

create table if not exists public.people (
  id           text primary key,
  display_name text        not null,
  calc_method  text        not null default 'NorthAmerica',
  asr_madhab   text        not null default 'standard',
  created_at   timestamptz not null default now()
);

insert into public.people (id, display_name) values
  ('khalid', 'Khalid'),
  ('marwa',  'Marwa')
on conflict (id) do nothing;

-- Where each person's qada count starts. Null means the date of their first
-- prayer log.
alter table public.people add column if not exists qada_start date;

-- Whether the Learn tab shows. On for Khalid, off for Marwa; only fills rows
-- that have no choice yet, so re-running keeps whatever was set in Settings.
alter table public.people add column if not exists show_learn boolean;
update public.people set show_learn = (id <> 'marwa') where show_learn is null;

-- The quick sends above the message box in the Us tab, edited in Settings.
-- Null means the defaults.
alter table public.people add column if not exists quick_sends jsonb;

-- ----------------------------------------------------------- prayer_logs -----

create table if not exists public.prayer_logs (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  log_date   date        not null,
  prayer     text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha')),
  status     text        not null check (status in ('on_time', 'late', 'missed')),
  updated_at timestamptz not null default now()
);

-- One row per person per prayer per day. Named constraint so that the client
-- can upsert with on_conflict=person,log_date,prayer.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.prayer_logs'::regclass
      and conname  = 'prayer_logs_person_log_date_prayer_key'
  ) then
    alter table public.prayer_logs
      add constraint prayer_logs_person_log_date_prayer_key
      unique (person, log_date, prayer);
  end if;
end $$;

create index if not exists prayer_logs_person_date_idx
  on public.prayer_logs (person, log_date);

create index if not exists prayer_logs_date_idx
  on public.prayer_logs (log_date desc);

-- Keep updated_at honest even if a client forgets to send it.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists prayer_logs_touch_updated_at on public.prayer_logs;
create trigger prayer_logs_touch_updated_at
  before update on public.prayer_logs
  for each row execute function public.touch_updated_at();

-- Realtime DELETE events only carry the primary key under the default replica
-- identity, which is not enough to know which prayer was cleared.
alter table public.prayer_logs replica identity full;

-- -------------------------------------------------------- quran_progress -----

-- Where each person last read: one row per person, upserted on person.
create table if not exists public.quran_progress (
  person     text        primary key references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  updated_at timestamptz not null default now()
);

drop trigger if exists quran_progress_touch_updated_at on public.quran_progress;
create trigger quran_progress_touch_updated_at
  before update on public.quran_progress
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------- quran_bookmarks -----

create table if not exists public.quran_bookmarks (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  created_at timestamptz not null default now()
);

-- One bookmark per ayah per person. Named so that the client can upsert with
-- on_conflict=person,surah,ayah.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.quran_bookmarks'::regclass
      and conname  = 'quran_bookmarks_person_surah_ayah_key'
  ) then
    alter table public.quran_bookmarks
      add constraint quran_bookmarks_person_surah_ayah_key
      unique (person, surah, ayah);
  end if;
end $$;

create index if not exists quran_bookmarks_person_created_idx
  on public.quran_bookmarks (person, created_at desc);

-- ------------------------------------------------------- hadith_progress -----

-- Where each person last read, in each collection: one row per person per
-- book, upserted on (person, book). Hadith numbers can be decimal (e.g. 402.2
-- in Bukhari), hence numeric.
create table if not exists public.hadith_progress (
  person        text          not null references public.people (id) on delete cascade,
  book          text          not null check (book ~ '^[a-z0-9]{1,32}$'),
  section       smallint      not null check (section >= 0),
  hadith_number numeric(10,2) not null check (hadith_number > 0),
  updated_at    timestamptz   not null default now(),
  primary key (person, book)
);

drop trigger if exists hadith_progress_touch_updated_at on public.hadith_progress;
create trigger hadith_progress_touch_updated_at
  before update on public.hadith_progress
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------ hadith_bookmarks -----

create table if not exists public.hadith_bookmarks (
  id            bigint generated by default as identity primary key,
  person        text          not null references public.people (id) on delete cascade,
  book          text          not null check (book ~ '^[a-z0-9]{1,32}$'),
  hadith_number numeric(10,2) not null check (hadith_number > 0),
  created_at    timestamptz   not null default now()
);

-- One bookmark per hadith per person. Named so that the client can upsert
-- with on_conflict=person,book,hadith_number.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.hadith_bookmarks'::regclass
      and conname  = 'hadith_bookmarks_person_book_hadith_number_key'
  ) then
    alter table public.hadith_bookmarks
      add constraint hadith_bookmarks_person_book_hadith_number_key
      unique (person, book, hadith_number);
  end if;
end $$;

create index if not exists hadith_bookmarks_person_created_idx
  on public.hadith_bookmarks (person, created_at desc);

-- ---------------------------------------------------------- qada_backlog -----

-- Prayers owed from before using Kharwa, entered by hand: one row per person
-- per prayer, upserted on (person, prayer). Witr is included since it is
-- wajib in the Hanafi school, though it is not tracked day to day.
create table if not exists public.qada_backlog (
  person     text        not null references public.people (id) on delete cascade,
  prayer     text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha', 'witr')),
  count      integer     not null default 0 check (count >= 0),
  updated_at timestamptz not null default now(),
  primary key (person, prayer)
);

drop trigger if exists qada_backlog_touch_updated_at on public.qada_backlog;
create trigger qada_backlog_touch_updated_at
  before update on public.qada_backlog
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------- push_subscriptions -----

-- Prayer reminders: one row per device that has turned them on, so a person
-- can have several. `keys` is the browser's { p256dh, auth }; `settings` is
-- { prayers: [...], minutes_before: 0 | 5 | 10 | 15 }. The send-reminders Edge
-- Function reads these every minute, and `last_sent` ("2026-10-09:asr") stops
-- a reminder going out twice. Upserted on endpoint.
create table if not exists public.push_subscriptions (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  endpoint   text        not null,
  keys       jsonb       not null,
  settings   jsonb       not null
             default '{"prayers": ["fajr", "dhuhr", "asr", "maghrib", "isha"], "minutes_before": 0}'::jsonb,
  last_sent  text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.push_subscriptions'::regclass
      and conname  = 'push_subscriptions_endpoint_key'
  ) then
    alter table public.push_subscriptions
      add constraint push_subscriptions_endpoint_key unique (endpoint);
  end if;
end $$;

create index if not exists push_subscriptions_person_idx
  on public.push_subscriptions (person);

drop trigger if exists push_subscriptions_touch_updated_at on public.push_subscriptions;
create trigger push_subscriptions_touch_updated_at
  before update on public.push_subscriptions
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- nudges -----

-- One row per nudge sent: "pray Isha", from one of you to the other. Written
-- by the send-nudge Edge Function, which allows one per prayer per direction
-- every 15 minutes; the app reads today's to show "nudged 3m ago".
create table if not exists public.nudges (
  id          bigint generated by default as identity primary key,
  from_person text        not null references public.people (id) on delete cascade,
  to_person   text        not null references public.people (id) on delete cascade,
  prayer      text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha')),
  log_date    date        not null,
  sent_at     timestamptz not null default now()
);

create index if not exists nudges_pair_day_idx
  on public.nudges (from_person, to_person, log_date, prayer, sent_at desc);

-- -------------------------------------------------------------- messages -----

-- The Us tab: messages between the two of you. `body` is the text, or for a
-- shared ayah or hadith its translation; `ref` says what was shared
-- ({ surah, ayah, ayah_to, name, arabic } or { book, number, name }), or for
-- a nudge { prayer, date }. A 'mood' message ("I'm stressed") has the mood's
-- id in `body`. Written by the send-message Edge Function (and
-- send-nudge for nudges); deleted after 30 days by the job in
-- supabase/messages-cron.sql.
create table if not exists public.messages (
  id          bigint generated by default as identity primary key,
  from_person text        not null references public.people (id) on delete cascade,
  to_person   text        not null references public.people (id) on delete cascade,
  type        text        not null check (type in ('text', 'ayah', 'hadith', 'nudge')),
  body        text        not null default '' check (char_length(body) <= 6000),
  ref         jsonb,
  note        text        check (char_length(note) <= 300),
  created_at  timestamptz not null default now(),
  read_at     timestamptz
);

-- 'mood' came later: the check is replaced, so re-running keeps it current.
alter table public.messages drop constraint if exists messages_type_check;
alter table public.messages add constraint messages_type_check
  check (type in ('text', 'ayah', 'hadith', 'nudge', 'mood'));

create index if not exists messages_created_idx
  on public.messages (created_at);

create index if not exists messages_to_unread_idx
  on public.messages (to_person, created_at) where read_at is null;

-- Realtime UPDATE and DELETE events carry the whole row, so "Seen" and a
-- deleted message reach the other phone.
alter table public.messages replica identity full;

-- ------------------------------------------------------------ us_presets -----

-- Ayahs either of you added to a mood in "Ayahs for the moment", from the
-- Quran tab. Shown to both, after the built-in ones in js/us-presets.js.
create table if not exists public.us_presets (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  mood       text        not null check (mood ~ '^[a-z]{1,24}$'),
  surah      smallint    not null check (surah between 1 and 114),
  ayah_from  smallint    not null check (ayah_from between 1 and 286),
  ayah_to    smallint    not null check (ayah_to between 1 and 286),
  created_at timestamptz not null default now(),
  check (ayah_to >= ayah_from)
);

-- One of each per mood, whoever added it. Named so that the client can
-- upsert with on_conflict=mood,surah,ayah_from,ayah_to.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.us_presets'::regclass
      and conname  = 'us_presets_mood_surah_ayah_from_ayah_to_key'
  ) then
    alter table public.us_presets
      add constraint us_presets_mood_surah_ayah_from_ayah_to_key
      unique (mood, surah, ayah_from, ayah_to);
  end if;
end $$;

-- -------------------------------------------------------------------- RLS ----

alter table public.people          enable row level security;
alter table public.prayer_logs     enable row level security;
alter table public.quran_progress  enable row level security;
alter table public.quran_bookmarks enable row level security;
alter table public.hadith_progress  enable row level security;
alter table public.hadith_bookmarks enable row level security;
alter table public.qada_backlog     enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.nudges             enable row level security;
alter table public.messages           enable row level security;
alter table public.us_presets         enable row level security;

-- Open policies for the anon role on every table, created only when missing.
do $$
declare
  tbl text;
begin
  foreach tbl in array array['people', 'prayer_logs', 'quran_progress', 'quran_bookmarks',
                             'hadith_progress', 'hadith_bookmarks', 'qada_backlog',
                             'push_subscriptions', 'nudges', 'messages', 'us_presets']
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to anon using (true)',
        tbl || '_anon_select', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_insert'
    ) then
      execute format(
        'create policy %I on public.%I for insert to anon with check (true)',
        tbl || '_anon_insert', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_update'
    ) then
      execute format(
        'create policy %I on public.%I for update to anon using (true) with check (true)',
        tbl || '_anon_update', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_delete'
    ) then
      execute format(
        'create policy %I on public.%I for delete to anon using (true)',
        tbl || '_anon_delete', tbl);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------- grants ----

grant usage on schema public to anon;
grant select, insert, update, delete on public.people          to anon;
grant select, insert, update, delete on public.prayer_logs     to anon;
grant select, insert, update, delete on public.quran_progress  to anon;
grant select, insert, update, delete on public.quran_bookmarks to anon;
grant select, insert, update, delete on public.hadith_progress  to anon;
grant select, insert, update, delete on public.hadith_bookmarks to anon;
grant select, insert, update, delete on public.qada_backlog     to anon;
grant select, insert, update, delete on public.push_subscriptions to anon;
grant select, insert, update, delete on public.nudges             to anon;
grant select, insert, update, delete on public.messages           to anon;
grant select, insert, update, delete on public.us_presets         to anon;
grant usage, select on all sequences in schema public to anon;

-- --------------------------------------------------------------- realtime ----

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  -- A "for all tables" publication already covers these and rejects
  -- explicit ADD TABLE, so only add when the publication is table-scoped.
  if not (select puballtables from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'prayer_logs'
    ) then
      alter publication supabase_realtime add table public.prayer_logs;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
    ) then
      alter publication supabase_realtime add table public.messages;
    end if;
  end if;
end $$;

notify pgrst, 'reload schema';
