-- Kharwa - schema
--
-- Paste this whole file into the Supabase SQL Editor and run it.
-- It is idempotent: re-running it is safe and will not drop data.
--
-- Note on security: there is no login in this app, so the anon role is granted
-- full read/write on every table. Anyone who has the project URL and anon key
-- can read and change the logs. That is a deliberate trade-off for a two-person
-- app on an unlisted URL.

-- ---------------------------------------------------------------- people -----

create table if not exists public.people (
  id           text primary key,
  display_name text        not null,
  calc_method  text        not null default 'NorthAmerica',
  asr_madhab   text        not null default 'standard',
  created_at   timestamptz not null default now()
);

insert into public.people (id, display_name) values
  ('khalid', 'Khalid'),
  ('marwa',  'Marwa')
on conflict (id) do nothing;

-- ----------------------------------------------------------- prayer_logs -----

create table if not exists public.prayer_logs (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  log_date   date        not null,
  prayer     text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha')),
  status     text        not null check (status in ('on_time', 'late', 'missed')),
  updated_at timestamptz not null default now()
);

-- One row per person per prayer per day. Named constraint so that the client
-- can upsert with on_conflict=person,log_date,prayer.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.prayer_logs'::regclass
      and conname  = 'prayer_logs_person_log_date_prayer_key'
  ) then
    alter table public.prayer_logs
      add constraint prayer_logs_person_log_date_prayer_key
      unique (person, log_date, prayer);
  end if;
end $$;

create index if not exists prayer_logs_person_date_idx
  on public.prayer_logs (person, log_date);

create index if not exists prayer_logs_date_idx
  on public.prayer_logs (log_date desc);

-- Keep updated_at honest even if a client forgets to send it.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists prayer_logs_touch_updated_at on public.prayer_logs;
create trigger prayer_logs_touch_updated_at
  before update on public.prayer_logs
  for each row execute function public.touch_updated_at();

-- Realtime DELETE events only carry the primary key under the default replica
-- identity, which is not enough to know which prayer was cleared.
alter table public.prayer_logs replica identity full;

-- -------------------------------------------------------- quran_progress -----

-- Where each person last read: one row per person, upserted on person.
create table if not exists public.quran_progress (
  person     text        primary key references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  updated_at timestamptz not null default now()
);

drop trigger if exists quran_progress_touch_updated_at on public.quran_progress;
create trigger quran_progress_touch_updated_at
  before update on public.quran_progress
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------- quran_bookmarks -----

create table if not exists public.quran_bookmarks (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  created_at timestamptz not null default now()
);

-- One bookmark per ayah per person. Named so that the client can upsert with
-- on_conflict=person,surah,ayah.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.quran_bookmarks'::regclass
      and conname  = 'quran_bookmarks_person_surah_ayah_key'
  ) then
    alter table public.quran_bookmarks
      add constraint quran_bookmarks_person_surah_ayah_key
      unique (person, surah, ayah);
  end if;
end $$;

create index if not exists quran_bookmarks_person_created_idx
  on public.quran_bookmarks (person, created_at desc);

-- -------------------------------------------------------------------- RLS ----

alter table public.people          enable row level security;
alter table public.prayer_logs     enable row level security;
alter table public.quran_progress  enable row level security;
alter table public.quran_bookmarks enable row level security;

-- Open policies for the anon role on every table, created only when missing.
do $$
declare
  tbl text;
begin
  foreach tbl in array array['people', 'prayer_logs', 'quran_progress', 'quran_bookmarks']
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to anon using (true)',
        tbl || '_anon_select', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_insert'
    ) then
      execute format(
        'create policy %I on public.%I for insert to anon with check (true)',
        tbl || '_anon_insert', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_update'
    ) then
      execute format(
        'create policy %I on public.%I for update to anon using (true) with check (true)',
        tbl || '_anon_update', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_delete'
    ) then
      execute format(
        'create policy %I on public.%I for delete to anon using (true)',
        tbl || '_anon_delete', tbl);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------- grants ----

grant usage on schema public to anon;
grant select, insert, update, delete on public.people          to anon;
grant select, insert, update, delete on public.prayer_logs     to anon;
grant select, insert, update, delete on public.quran_progress  to anon;
grant select, insert, update, delete on public.quran_bookmarks to anon;
grant usage, select on all sequences in schema public to anon;

-- --------------------------------------------------------------- realtime ----

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  -- A "for all tables" publication already covers prayer_logs and rejects
  -- explicit ADD TABLE, so only add when the publication is table-scoped.
  if not (select puballtables from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename  = 'prayer_logs'
     )
  then
    alter publication supabase_realtime add table public.prayer_logs;
  end if;
end $$;

notify pgrst, 'reload schema';
