-- Kharwa - schema
--
-- Paste this whole file into the Supabase SQL Editor and run it.
-- It is idempotent: re-running it is safe and will not drop data.
--
-- Note on security: there is no login in this app, so the anon role is granted
-- full read/write on every table. Anyone who has the project URL and anon key
-- can read and change the logs. That is a deliberate trade-off for a two-person
-- app on an unlisted URL.

-- ---------------------------------------------------------------- people -----

create table if not exists public.people (
  id           text primary key,
  display_name text        not null,
  calc_method  text        not null default 'NorthAmerica',
  asr_madhab   text        not null default 'standard',
  created_at   timestamptz not null default now()
);

insert into public.people (id, display_name) values
  ('khalid', 'Khalid'),
  ('marwa',  'Marwa')
on conflict (id) do nothing;

-- Where each person's qada count starts. Null means the date of their first
-- prayer log.
alter table public.people add column if not exists qada_start date;

-- Whether the Learn tab shows. On for Khalid, off for Marwa; only fills rows
-- that have no choice yet, so re-running keeps whatever was set in Settings.
alter table public.people add column if not exists show_learn boolean;
update public.people set show_learn = (id <> 'marwa') where show_learn is null;

-- ----------------------------------------------------------- prayer_logs -----

create table if not exists public.prayer_logs (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  log_date   date        not null,
  prayer     text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha')),
  status     text        not null check (status in ('on_time', 'late', 'missed')),
  updated_at timestamptz not null default now()
);

-- One row per person per prayer per day. Named constraint so that the client
-- can upsert with on_conflict=person,log_date,prayer.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.prayer_logs'::regclass
      and conname  = 'prayer_logs_person_log_date_prayer_key'
  ) then
    alter table public.prayer_logs
      add constraint prayer_logs_person_log_date_prayer_key
      unique (person, log_date, prayer);
  end if;
end $$;

create index if not exists prayer_logs_person_date_idx
  on public.prayer_logs (person, log_date);

create index if not exists prayer_logs_date_idx
  on public.prayer_logs (log_date desc);

-- Keep updated_at honest even if a client forgets to send it.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists prayer_logs_touch_updated_at on public.prayer_logs;
create trigger prayer_logs_touch_updated_at
  before update on public.prayer_logs
  for each row execute function public.touch_updated_at();

-- Realtime DELETE events only carry the primary key under the default replica
-- identity, which is not enough to know which prayer was cleared.
alter table public.prayer_logs replica identity full;

-- -------------------------------------------------------- quran_progress -----

-- Where each person last read: one row per person, upserted on person.
create table if not exists public.quran_progress (
  person     text        primary key references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  updated_at timestamptz not null default now()
);

drop trigger if exists quran_progress_touch_updated_at on public.quran_progress;
create trigger quran_progress_touch_updated_at
  before update on public.quran_progress
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------- quran_bookmarks -----

create table if not exists public.quran_bookmarks (
  id         bigint generated by default as identity primary key,
  person     text        not null references public.people (id) on delete cascade,
  surah      smallint    not null check (surah between 1 and 114),
  ayah       smallint    not null check (ayah between 1 and 286),
  created_at timestamptz not null default now()
);

-- One bookmark per ayah per person. Named so that the client can upsert with
-- on_conflict=person,surah,ayah.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.quran_bookmarks'::regclass
      and conname  = 'quran_bookmarks_person_surah_ayah_key'
  ) then
    alter table public.quran_bookmarks
      add constraint quran_bookmarks_person_surah_ayah_key
      unique (person, surah, ayah);
  end if;
end $$;

create index if not exists quran_bookmarks_person_created_idx
  on public.quran_bookmarks (person, created_at desc);

-- ------------------------------------------------------- hadith_progress -----

-- Where each person last read, in each collection: one row per person per
-- book, upserted on (person, book). Hadith numbers can be decimal (e.g. 402.2
-- in Bukhari), hence numeric.
create table if not exists public.hadith_progress (
  person        text          not null references public.people (id) on delete cascade,
  book          text          not null check (book ~ '^[a-z0-9]{1,32}$'),
  section       smallint      not null check (section >= 0),
  hadith_number numeric(10,2) not null check (hadith_number > 0),
  updated_at    timestamptz   not null default now(),
  primary key (person, book)
);

drop trigger if exists hadith_progress_touch_updated_at on public.hadith_progress;
create trigger hadith_progress_touch_updated_at
  before update on public.hadith_progress
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------ hadith_bookmarks -----

create table if not exists public.hadith_bookmarks (
  id            bigint generated by default as identity primary key,
  person        text          not null references public.people (id) on delete cascade,
  book          text          not null check (book ~ '^[a-z0-9]{1,32}$'),
  hadith_number numeric(10,2) not null check (hadith_number > 0),
  created_at    timestamptz   not null default now()
);

-- One bookmark per hadith per person. Named so that the client can upsert
-- with on_conflict=person,book,hadith_number.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.hadith_bookmarks'::regclass
      and conname  = 'hadith_bookmarks_person_book_hadith_number_key'
  ) then
    alter table public.hadith_bookmarks
      add constraint hadith_bookmarks_person_book_hadith_number_key
      unique (person, book, hadith_number);
  end if;
end $$;

create index if not exists hadith_bookmarks_person_created_idx
  on public.hadith_bookmarks (person, created_at desc);

-- ---------------------------------------------------------- qada_backlog -----

-- Prayers owed from before using Kharwa, entered by hand: one row per person
-- per prayer, upserted on (person, prayer). Witr is included since it is
-- wajib in the Hanafi school, though it is not tracked day to day.
create table if not exists public.qada_backlog (
  person     text        not null references public.people (id) on delete cascade,
  prayer     text        not null check (prayer in ('fajr', 'dhuhr', 'asr', 'maghrib', 'isha', 'witr')),
  count      integer     not null default 0 check (count >= 0),
  updated_at timestamptz not null default now(),
  primary key (person, prayer)
);

drop trigger if exists qada_backlog_touch_updated_at on public.qada_backlog;
create trigger qada_backlog_touch_updated_at
  before update on public.qada_backlog
  for each row execute function public.touch_updated_at();

-- -------------------------------------------------------------------- RLS ----

alter table public.people          enable row level security;
alter table public.prayer_logs     enable row level security;
alter table public.quran_progress  enable row level security;
alter table public.quran_bookmarks enable row level security;
alter table public.hadith_progress  enable row level security;
alter table public.hadith_bookmarks enable row level security;
alter table public.qada_backlog     enable row level security;

-- Open policies for the anon role on every table, created only when missing.
do $$
declare
  tbl text;
begin
  foreach tbl in array array['people', 'prayer_logs', 'quran_progress', 'quran_bookmarks',
                             'hadith_progress', 'hadith_bookmarks', 'qada_backlog']
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_select'
    ) then
      execute format(
        'create policy %I on public.%I for select to anon using (true)',
        tbl || '_anon_select', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_insert'
    ) then
      execute format(
        'create policy %I on public.%I for insert to anon with check (true)',
        tbl || '_anon_insert', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_update'
    ) then
      execute format(
        'create policy %I on public.%I for update to anon using (true) with check (true)',
        tbl || '_anon_update', tbl);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = tbl
        and policyname = tbl || '_anon_delete'
    ) then
      execute format(
        'create policy %I on public.%I for delete to anon using (true)',
        tbl || '_anon_delete', tbl);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------- grants ----

grant usage on schema public to anon;
grant select, insert, update, delete on public.people          to anon;
grant select, insert, update, delete on public.prayer_logs     to anon;
grant select, insert, update, delete on public.quran_progress  to anon;
grant select, insert, update, delete on public.quran_bookmarks to anon;
grant select, insert, update, delete on public.hadith_progress  to anon;
grant select, insert, update, delete on public.hadith_bookmarks to anon;
grant select, insert, update, delete on public.qada_backlog     to anon;
grant usage, select on all sequences in schema public to anon;

-- --------------------------------------------------------------- realtime ----

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  -- A "for all tables" publication already covers prayer_logs and rejects
  -- explicit ADD TABLE, so only add when the publication is table-scoped.
  if not (select puballtables from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename  = 'prayer_logs'
     )
  then
    alter publication supabase_realtime add table public.prayer_logs;
  end if;
end $$;

notify pgrst, 'reload schema';
